### ISSUE TITLE
Add a formatter for TCP logging

### ISSUE THREAD

**Issue by bmoe** [svetob/logstash-json#22]
I'm finding I need to mess around with some of the hard-coded attributes in the log message.  For instance, our logstash expects 'level' to be in integer -- if we send strings, we have trouble.  Same with 'pid'.

Might it be possible to have a configurable formatter that can dynamically modify the log event?  So we could do something like:
```elixir
config :logger, :logstash
   formatter: {MyApp, :formatter}
```
with module `MyApp` having
``` elixir
def formatter(event) do
   event
   |> Map.put(:thread_id, event[:pid])
   |> Map.put(:level, convert_level(event[:level])
   |> Map.delete(:pid)
end
```
Does this make sense?   I did a quick and dirty you can look at in my fork.  I'll add tests and docs if this is of interest to you.  Also -- am pretty new to Elixir and am open to criticism and guidance.

Thanks!

**Comment by svetob** [comment]
Now available in the 0.7.0 release.
