### ISSUE TITLE
Unchecked dependencies for environment tes

### ISSUE THREAD

**Issue by mustela** [svetob/logstash-json#32]
Hey there! 

I just add the lib to my project `{:logstash, github: "svetob/logstash-json"}` and when I try to run tests or the app Im getting: 
```
Unchecked dependencies for environment test:
* logstash (https://github.com/svetob/logstash-json.git)
  could not find an app file at "_build/test/lib/logstash/ebin/logstash.app". This may happen if the dependency was not yet compiled, or you specified the wrong application name in your deps, or the dependency indeed has no app file (then you can pass app: false as option)
** (Mix) Can't continue due to errors on dependencies
```

Any clue? Thanks!

**Comment by dalefrancis88** [comment]
I'm getting the same on mine, i'm very inexperienced with Elixir so i'm guessing its something simple, were you able to solve?

**Comment by mustela** [comment]
Same here, Im new with Elixir. Nothing seems to be working. I've cleaned/reinstalled/changed versions, etc and same error :/

**Comment by svetob** [comment]
It looks like the problem is the dependency import example in the README are outdated. The dep import should look like this:

```
{:logstash_json, "~> 0.7"}
```

Updated the README to match.

**Comment by dalefrancis88** [comment]
Thanks for looking into that @svetob
